### ISSUE TITLE
Add new functionality to add new bank account data

### ISSUE THREAD

**Issue by Ni3verma** [Ni3verma/Safe-Box#12]
On the home page when user clicks on "Bank account",
![image](https://user-images.githubusercontent.com/20037625/121799627-cafa9c80-cc4a-11eb-8716-bb6b2de7e014.png)

get required details from user and store in db.

This feature will be very similar to feature implemented in "feature/add new login data" branch #11 

## what you will learn
* Using Room db
* making a whole new screen with viewmodels,repo,fragment all in MVVM pattern
* using Hilt to manage dependency for this new feature
* using coroutines
* live data and data binding
* .. more

fields to show in UI (* are mandatory):
1. title *
2. account number *
3. customer name
4. customer Id *
5. branch code
6. branch name
7. branch address
8. IFSC code *
9. MICR code
10. Notes

fields to add in new DB table
1. key (autogenerated)*
2. account number *
3. customer name
4. customer Id *
5. branch code
6. branch name
7. branch address
8. IFSC code *
9. MICR code
10. Notes
11. title*
12. creationDate*
13. updateDate*

**Comment by kunchammahajan** [comment]
Hi Nitin , I want to work on this issue
