### ISSUE TITLE
Feature Request : Add new app icon

### ISSUE THREAD

**Issue by Ni3verma** [Ni3verma/Safe-Box#26]
**Is your feature request related to a problem? Please describe.**
NA

**Describe the solution you'd like**
Suggest a new icon for app

**Additional context**
Icon should describe the core functionality of this app : security

**Comment by Ni3verma** [comment]
![image](https://user-images.githubusercontent.com/20037625/124376034-96668780-dcc2-11eb-8d47-04ae7f362f35.png)

This is the best I can design

**Comment by Bhawna-Ad** [comment]
Hi! Please checkout my design for the app icon

<img src="https://user-images.githubusercontent.com/70805716/125185096-434f8000-e240-11eb-9f78-d56a7f361609.png" width=300>

**Comment by Ni3verma** [comment]
@Bhawna-Ad  Assigning it to you, Please make a PR for this.
