### ISSUE TITLE
Add Hint functionality for user login password

### ISSUE THREAD

**Issue by Ni3verma** [Ni3verma/Safe-Box#3]
- Add functionality for users to add hint while adding a master password
- Show option to see hint on login page
- store hint in user data table as encypted string

validations while adding hint:
- hint should not contain 5 consecutive letters of user password.
- upper limit on hint length = 30

**Comment by Bhawna-Ad** [comment]
Hello! I would like to work on this issue. Can you suggest me how to get started?

**Comment by Ni3verma** [comment]
Hi @Bhawna-Ad , first read the [contributing ](https://github.com/Ni3verma/Safe-Box/blob/master/CONTRIBUTING.md) guidelines. Let me know if you face any issue here.
and then start with adding a new text box here : choose_master_pswrd_fragment.xml

then pass the same string in its view model in place of "ADD HINT IN UI"
```
fun onSaveClick() {
        Timber.i("save password clicked")
        viewModelScope.launch {
            userDetailsRepository.insertUserDetailsData(pswrd.value!!, "ADD HINT IN UI")
            encryptedPreferenceProvider.upsertBooleanPref(IS_SIGN_UP_REQUIRED, false)
            Timber.i("Added pswrd in db")
            _navigateToHome.value = true
        }
    }
```

first do this, then we can discuss on validation part.

**Comment by Bhawna-Ad** [comment]
Alright, Thanks!😀 I will get back to you once I am done with the same.

**Comment by Bhawna-Ad** [comment]
Hi! I have made the following changes : 
1.  Added a textfield to get the hint input.
2. Passed the  hint string to ChooseMasterPswrdViewModel

Before adding the constraints for the hint, I want to make sure that I am going right, so should I make a PR for that or any other way that you would suggest?

**Comment by Ni3verma** [comment]
yes please make a draft PR

**Comment by Bhawna-Ad** [comment]
I have created a draft pull request. Please review the changes.
